---

- name: generic software installation
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - vim
      - tmux
      - git
      - ufw
      - dnsmasq
